version: "3.8"

services:
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - backend/.env
    networks:
      - usjm_network

  backend:
    depends_on:
      - db
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes: 
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - backend/.env
    networks:
      - usjm_network
    restart: unless-stopped

  frontend:
    depends_on:
      - db
      - backend
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3333:3000"
    stdin_open: true
    tty: true
    networks:
      - usjm_network
    restart: unless-stopped

networks:
  usjm_network: