version: "3.8"

services:
	database:
		container_name: database
		image: postgres:latest
		env_file:
			- backend/.env
		networks:
			- mynetwork

	backend:
		depends_on:
			- database
		container_name: backend
		build:
			context: ./backend
			dockerfile: Dockerfile
		volumes:
			- ./backend:/app
			- /app/node_modules
		ports:
			- "3000:3000"
			- "5555:5555"
		env_file:
			- backend/.env
		networks:
			- mynetwork

	# frontend:
	#   container_name: frontend
	#   restart: always
	#   build:
	#     context: ./frontend
	#     dockerfile: Dockerfile
	#   volumes:
	#     - ./frontend:/app
	#     - /app/node_modules
	#   ports:
	#     - "3333:3000"
	#   env_file:
	#     - backend/.env
	#   command: ["yarn", "dev", "--host", "0.0.0.0"]
	#   networks:
	#     - mynetwork

networks:
	mynetwork: